logging:
  level: INFO
  loggers:
    com.javaperks.api: DEBUG
server:
  applicationConnectors:
  - type: http
    port: 5822
  adminConnectors:
  - type: http
    port: 9001
vaultAddress: ""
vaultToken: ""
dbAddress: ""
dbUsername: ""
dbPassword: ""
dbDatabase: "javaperks"