FROM ubuntu:18.04
  
MAINTAINER Kevin Cochran "kcochran@hashicorp.com"

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y python3 python3-pip
RUN mkdir /app

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip3 install -r requirements.txt

COPY ./cust-app.py /app
COPY ./creds.json /app

ENTRYPOINT [ "python3" ]

CMD [ "cust-app.py" ]
